initial kafka-consumer commit
nttgin/BGPalerter pull request #603
Opened 2021-07-14 17:34 UTC by kbmanseau

This is the inital submission of the kafka consumer code. More to come

2021-07-19 12:48 UTC, massimocandela requested changes
Thanks @kbmanseau for your contribution. 

I added some comments. In addition to the comments and to an overall polishing of the code, the following is missing:
- test, to automatically check the kafka connector by spawning a kafka instance and injecting data (see reportKafka tests);
- documentation, describing how to use the connector.

Also, in reportKafka I used kafkajs (which is already part of the dependencies). kafka-node is an abandoned project which currently has several bugs and old dependencies. Please, switch to kafkajs.

Thanks!

2021-07-19 12:48 UTC, massimocandela commented on src/connectors/connectorKAF.js
> +    _subscribeToAll = (input) => {
This method must be implemented or the `carefulSubscription` option should be removed

2021-07-19 12:48 UTC, massimocandela commented on src/connectors/connectorKAF.js
> +                var kafka = require('kafka-node');
import kafka at the beginning. Use let or const, not var.

2021-07-19 12:48 UTC, massimocandela commented on src/connectors/connectorKAF.js
> +    _optimizedPathMatch = (regex) => {
this method can be removed because there is no need for path optimizations in this case

2021-07-19 12:48 UTC, massimocandela commented on src/connectors/connectorKAF.js
> +        this.connect()
It looks like every time the input file changes, a new kafka connection is established without closing the previous one. Am I correct?

2021-07-19 12:48 UTC, massimocandela commented on src/connectors/connectorKAF.js
> +        this.url = brembo.build(this.params.url, {
this is not used

2021-08-20 15:18 UTC, kbmanseau commented
Thank you for the feedback. It has been really busy lately but will work on addressing your feedback in the coming weeks

2021-11-17 03:07 UTC, a16 commented
Any updates on this PR? I'm very interested in this function. It would be useful that BGPalerter can monitor not only RISLive but also other sources (e.g. BMP, etc).

2021-11-17 16:18 UTC, kbmanseau commented
Hi @a16, that is the exact use case we are using. We collect BMP data, feed to a kafka broker and then consume that with BGPAlerter. Its been a while since I last looked but I believe that we are running the code in this PR in our environment without issue. 

Regarding the changes suggested by @massimocandela, unfortunately this has fallen into the backlog for me as other high priority items have surfaced. I still plan to go back and make the suggested changes but that may take some time

2022-01-12 14:35 UTC, kbmanseau commented
@massimocandela I wanted to thank you again for the feedback you have provided. I have started implementing some of it and mainly focused on kafka-node -> kafka-js. I will be continuing to address feedback

2022-02-25 21:09 UTC, kbmanseau commented
@massimocandela I had a question regarding monitoring. We are trying to monitor much more than just our own ASN so for now we have made some queries to apis to return prefixes and their ASNs. This then gets parsed into the prefixes.yml for BGPAlerter.

I think there are many challenges to this but do you think there is there a way that one could "Monitor everything"? One large challenge I think would be establishing the source of truth as this is done through the config/prefix files

2022-06-13 00:02 UTC, closed without merging